'use client';

import React, { useState } from 'react';
import { useDocument } from '@/context/DocumentContext';
import {
  CheckSquare,
  Square,
  Sparkles,
  MessageSquareQuote,
  Copy,
  Check,
  Plus,
  ArrowRight,
  FileCheck,
  Printer,
  Scale,
  Download,
  Filter,
  RotateCcw
} from 'lucide-react';
import { cn } from '@/lib/utils';
import Link from 'next/link';

export default function ChecklistPage() {
  const { currentDocument, toggleChecklistItem, addCustomChecklistItem, setCurrentDocument } = useDocument();

  const [copiedAll, setCopiedAll] = useState(false);
  const [copiedQuestionId, setCopiedQuestionId] = useState<string | null>(null);
  const [selectedFilter, setSelectedFilter] = useState<string>('All');
  const [newItemText, setNewItemText] = useState('');
  const [newItemCategory, setNewItemCategory] = useState<
    'Immediate' | 'Pre-Signing' | 'Ongoing' | 'Legal Consultation'
  >('Pre-Signing');

  const categories = ['All', 'Pre-Signing', 'Immediate', 'Ongoing', 'Legal Consultation'];

  const filteredChecklist = currentDocument.checklist.filter((item) => {
    if (selectedFilter === 'All') return true;
    return item.category === selectedFilter;
  });

  const completedCount = currentDocument.checklist.filter((c) => c.completed).length;
  const totalCount = currentDocument.checklist.length;
  const progressPercent = totalCount > 0 ? Math.round((completedCount / totalCount) * 100) : 0;

  const handleCopyLawyerPrep = () => {
    const text = `NYAYALENS LEGAL COUNSEL PREPARATION BRIEF
Document: ${currentDocument.name}
Parties: ${currentDocument.parties.join(' & ')}
Jurisdiction: ${currentDocument.governingLaw}

KEY QUESTIONS TO DISCUSS WITH LEGAL ADVISOR:
${currentDocument.lawyerQuestions
  .map(
    (q, i) =>
      `${i + 1}. ${q.question}\n   Context: ${q.rationale}\n   Reference: ${q.relatedClause}`
  )
  .join('\n\n')}

Disclaimer: Generated by NyayaLens for informational consultation prep. Does not constitute legal advice.`;

    navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2500);
  };

  const handleCopySingleQuestion = (id: string, question: string) => {
    navigator.clipboard.writeText(question);
    setCopiedQuestionId(id);
    setTimeout(() => setCopiedQuestionId(null), 2000);
  };

  const handleExportChecklist = () => {
    const content = `NYAYALENS ACTION DILIGENCE CHECKLIST
Document: ${currentDocument.name}
Generated: ${new Date().toLocaleDateString()}
Completion Status: ${completedCount}/${totalCount} (${progressPercent}%)

CHECKLIST ITEMS:
${currentDocument.checklist
  .map(
    (item) =>
      `[${item.completed ? 'X' : ' '}] (${item.category}) ${item.text}${
        item.deadline ? ` - Due: ${item.deadline}` : ''
      }${item.note ? `\n    Note: ${item.note}` : ''}`
  )
  .join('\n')}

LAWYER PREPARATION QUESTIONS:
${currentDocument.lawyerQuestions
  .map((q, i) => `${i + 1}. ${q.question} (${q.relatedClause})`)
  .join('\n')}

Disclaimer: Informational assistance only. Does not replace professional legal counsel.`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${currentDocument.name.replace(/\s+/g, '_')}_Checklist.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleAddCustom = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemText.trim()) return;
    addCustomChecklistItem(newItemText.trim(), newItemCategory);
    setNewItemText('');
  };

  const handleToggleAll = () => {
    const allDone = completedCount === totalCount;
    const updated = currentDocument.checklist.map((c) => ({
      ...c,
      completed: !allDone
    }));
    setCurrentDocument({
      ...currentDocument,
      checklist: updated
    });
  };

  return (
    <div className="flex-1 max-w-5xl mx-auto w-full px-4 sm:px-6 lg:px-8 py-8 space-y-8 animate-fade-in">
      {/* 1. Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl sm:text-3xl font-black text-slate-950 tracking-tight">
              Your Legal Action Checklist
            </h1>
            <span className="text-xs px-2.5 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200 font-semibold">
              Action Plan
            </span>
          </div>
          <p className="text-slate-600 text-sm mt-1">
            Generated step-by-step verification checklist for <strong>{currentDocument.name}</strong>.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            onClick={handleExportChecklist}
            aria-label="Export diligence checklist as text file"
            className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl border border-slate-200 hover:bg-slate-100 text-xs font-semibold text-slate-700 transition focus:outline-none focus:ring-2 focus:ring-slate-500"
            title="Download checklist text file"
          >
            <Download className="w-3.5 h-3.5 text-slate-600" aria-hidden="true" />
            <span className="hidden sm:inline">Export Text</span>
          </button>

          <button
            type="button"
            onClick={() => window.print()}
            aria-label="Print action checklist"
            className="hidden sm:inline-flex items-center gap-1.5 px-3 py-2 rounded-xl border border-slate-200 hover:bg-slate-100 text-xs font-semibold text-slate-700 transition focus:outline-none focus:ring-2 focus:ring-slate-500"
          >
            <Printer className="w-3.5 h-3.5 text-slate-600" aria-hidden="true" />
            <span>Print</span>
          </button>

          <button
            type="button"
            onClick={handleCopyLawyerPrep}
            aria-label="Copy legal consultation brief to clipboard"
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold shadow-subtle transition focus:outline-none focus:ring-2 focus:ring-slate-900"
          >
            {copiedAll ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" aria-hidden="true" />
                <span>Copied Brief!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-indigo-300" aria-hidden="true" />
                <span>Copy Consultation Brief</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* 2. Progress Strip */}
      <section aria-labelledby="checklist-progress-title" className="bg-white p-5 rounded-2xl border border-slate-200 shadow-subtle space-y-3">
        <h2 id="checklist-progress-title" className="sr-only">Checklist Completion Progress</h2>
        <div className="flex items-center justify-between text-xs font-semibold">
          <div className="flex items-center gap-2">
            <span className="text-slate-900 font-bold">Checklist Completion Status</span>
            <span className="text-slate-600 font-medium">
              ({completedCount} of {totalCount} completed)
            </span>
          </div>
          <span className="font-mono text-indigo-700 font-bold">{progressPercent}%</span>
        </div>

        <div
          role="progressbar"
          aria-valuenow={progressPercent}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label="Checklist completion percentage"
          className="w-full h-2.5 rounded-full bg-slate-100 overflow-hidden"
        >
          <div
            className="h-full bg-gradient-to-r from-indigo-600 to-emerald-500 rounded-full transition-all duration-300"
            style={{ width: `${progressPercent}%` }}
          />
        </div>
      </section>

      {/* 3. Interactive Checklist Items */}
      <section aria-labelledby="checklist-items-title" className="bg-white rounded-2xl border border-slate-200 p-6 shadow-subtle space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
          <div>
            <h2 id="checklist-items-title" className="text-base font-bold text-slate-900">
              Action Items & Diligence Tasks
            </h2>
            <span className="text-xs text-slate-600">Click any item to toggle completion</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleToggleAll}
              aria-label={completedCount === totalCount ? 'Unmark all checklist items' : 'Mark all checklist items complete'}
              className="text-xs text-indigo-700 hover:text-indigo-900 font-semibold px-2.5 py-1 rounded bg-indigo-50 border border-indigo-200 transition focus:outline-none focus:ring-2 focus:ring-indigo-500"
            >
              {completedCount === totalCount ? 'Unmark All' : 'Mark All Complete'}
            </button>
          </div>
        </div>

        {/* Category Filters */}
        <div role="group" aria-label="Filter checklist items by category" className="flex items-center gap-1.5 overflow-x-auto pb-1">
          <span className="text-xs font-semibold text-slate-600 flex items-center gap-1">
            <Filter className="w-3.5 h-3.5 text-slate-500" aria-hidden="true" />
            Category:
          </span>
          {categories.map((cat) => (
            <button
              key={cat}
              type="button"
              aria-pressed={selectedFilter === cat}
              onClick={() => setSelectedFilter(cat)}
              className={cn(
                'px-3 py-1 rounded-lg text-xs font-semibold transition whitespace-nowrap focus:outline-none focus:ring-2 focus:ring-slate-500',
                selectedFilter === cat
                  ? 'bg-slate-900 text-white'
                  : 'bg-slate-50 text-slate-700 hover:bg-slate-100'
              )}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Items List */}
        <div className="space-y-3">
          {filteredChecklist.map((item) => (
            <div
              key={item.id}
              onClick={() => toggleChecklistItem(item.id)}
              className={cn(
                'p-4 rounded-xl border transition-all cursor-pointer flex items-start gap-3 select-none',
                item.completed
                  ? 'bg-slate-50 border-slate-200'
                  : 'bg-white border-slate-200 hover:border-indigo-300 hover:shadow-subtle'
              )}
            >
              <button
                type="button"
                role="checkbox"
                aria-checked={item.completed}
                aria-label={`Mark "${item.text}" as ${item.completed ? 'incomplete' : 'complete'}`}
                className="mt-0.5 shrink-0 text-indigo-600 transition focus:outline-none focus:ring-2 focus:ring-indigo-500 rounded"
              >
                {item.completed ? (
                  <CheckSquare className="w-5 h-5 text-emerald-600" aria-hidden="true" />
                ) : (
                  <Square className="w-5 h-5 text-slate-500" aria-hidden="true" />
                )}
              </button>

              <div className="flex-1 space-y-1">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span
                    className={cn(
                      'text-xs font-semibold',
                      item.completed ? 'line-through text-slate-600' : 'text-slate-900'
                    )}
                  >
                    {item.text}
                  </span>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-100 text-slate-700">
                    {item.category}
                  </span>
                </div>

                {item.note && (
                  <p className="text-[11px] text-slate-600">
                    Note: {item.note}
                  </p>
                )}

                {item.deadline && (
                  <span className="text-[10px] font-mono text-indigo-700 block font-semibold">
                    Deadline: {item.deadline}
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Add custom item form */}
        <form onSubmit={handleAddCustom} className="pt-4 border-t border-slate-100 flex flex-col sm:flex-row gap-2">
          <label htmlFor="new-checklist-text" className="sr-only">
            Add custom diligence note or verification item
          </label>
          <input
            id="new-checklist-text"
            type="text"
            placeholder="Add custom diligence note or verification item..."
            aria-label="Add custom diligence note or verification item"
            value={newItemText}
            onChange={(e) => setNewItemText(e.target.value)}
            className="flex-1 px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg text-slate-900 placeholder:text-slate-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
          />

          <label htmlFor="new-checklist-category" className="sr-only">
            Select diligence item category
          </label>
          <select
            id="new-checklist-category"
            aria-label="Select diligence item category"
            value={newItemCategory}
            onChange={(e) => setNewItemCategory(e.target.value as any)}
            className="px-3 py-2 text-xs bg-slate-50 border border-slate-200 rounded-lg text-slate-700 font-medium focus:outline-none focus:ring-1 focus:ring-indigo-500"
          >
            <option value="Pre-Signing">Pre-Signing</option>
            <option value="Immediate">Immediate</option>
            <option value="Ongoing">Ongoing</option>
            <option value="Legal Consultation">Legal Consultation</option>
          </select>

          <button
            type="submit"
            disabled={!newItemText.trim()}
            aria-label="Add item to checklist"
            className="inline-flex items-center justify-center gap-1 px-4 py-2 rounded-lg bg-slate-900 hover:bg-slate-800 disabled:opacity-40 text-white text-xs font-semibold transition focus:outline-none focus:ring-2 focus:ring-slate-900"
          >
            <Plus className="w-3.5 h-3.5" aria-hidden="true" />
            <span>Add Item</span>
          </button>
        </form>
      </section>

      {/* 4. Prepare Questions for a Lawyer Section */}
      <section aria-labelledby="lawyer-questions-title" className="bg-gradient-to-br from-indigo-50/80 via-white to-slate-50 rounded-2xl border border-indigo-200/80 p-6 shadow-subtle space-y-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-indigo-100">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-indigo-600 text-white flex items-center justify-center" aria-hidden="true">
              <Scale className="w-5 h-5" />
            </div>
            <div>
              <h2 id="lawyer-questions-title" className="text-base font-bold text-slate-900">
                Prepare Questions for a Lawyer
              </h2>
              <p className="text-xs text-slate-600">
                Framed for consultation preparation to maximize your meeting efficiency
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={handleCopyLawyerPrep}
            aria-label="Copy all legal consultation questions to clipboard"
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-indigo-200 hover:bg-indigo-100/70 text-indigo-900 text-xs font-semibold transition shadow-2xs focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            <Copy className="w-3.5 h-3.5 text-indigo-600" aria-hidden="true" />
            <span>Copy All Questions</span>
          </button>
        </div>

        <div className="space-y-3">
          {currentDocument.lawyerQuestions.map((q, idx) => (
            <div
              key={q.id}
              className="p-4 rounded-xl bg-white border border-indigo-100 text-xs space-y-2 shadow-2xs"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-start gap-2 flex-1">
                  <span className="w-5 h-5 rounded-full bg-indigo-100 text-indigo-800 flex items-center justify-center font-bold text-[11px] shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <div className="space-y-1">
                    <h3 className="font-bold text-slate-900 text-xs sm:text-sm">
                      "{q.question}"
                    </h3>
                    <p className="text-[11px] text-slate-700 leading-relaxed">
                      <strong>Rationale:</strong> {q.rationale}
                    </p>
                    <div className="text-[10px] font-mono text-indigo-700 pt-1 font-semibold">
                      Related Section: {q.relatedClause}
                    </div>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => handleCopySingleQuestion(q.id, q.question)}
                  className="shrink-0 p-1.5 rounded-lg text-slate-600 hover:text-indigo-700 hover:bg-indigo-50 transition focus:outline-none focus:ring-1 focus:ring-indigo-500"
                  title="Copy question"
                  aria-label={`Copy question: "${q.question}"`}
                >
                  {copiedQuestionId === q.id ? (
                    <Check className="w-4 h-4 text-emerald-600" aria-hidden="true" />
                  ) : (
                    <Copy className="w-4 h-4" aria-hidden="true" />
                  )}
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="p-3 bg-amber-50 rounded-xl border border-amber-200 text-amber-900 text-[11px] leading-relaxed flex items-start gap-2">
          <MessageSquareQuote className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" aria-hidden="true" />
          <span>
            <strong>Professional Consultation Disclaimer:</strong> These questions are structured to help you organize your discussion with an attorney. Bring this sheet and your contract to your consultation.
          </span>
        </div>
      </section>
    </div>
  );
}
